# Generated by Django 5.1 on 2026-03-18 06:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('vision', 'Vision Test (Snellen)'), ('colorblind', 'Color Blindness Test'), ('dryeye', 'Dry Eye (OSDI) Test'), ('blink', 'Blink Rate Test')], max_length=20)),
                ('result_data', models.JSONField(default=dict, help_text='Flexible JSON storage for test-specific results')),
                ('score', models.CharField(blank=True, help_text='Human-readable score summary', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screening Test Result',
                'verbose_name_plural': 'Screening Test Results',
                'ordering': ['-created_at'],
            },
        ),
    ]
