# Generated by Django 5.1.5 on 2026-02-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometrist',
            name='role',
            field=models.CharField(choices=[('optometrist', 'Optometrist'), ('doctor', 'Doctor')], default='optometrist', max_length=20),
        ),
    ]
