# Generated by Django 5.1.5 on 2026-02-07 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0003_patient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='complaint',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='findings',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='optometrist',
        ),
        migrations.CreateModel(
            name='EyeExamination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_visit', models.DateField(auto_now_add=True)),
                ('chief_complaints', models.TextField(blank=True)),
                ('systemic_history', models.TextField(blank=True, default='NA')),
                ('screen_time', models.CharField(blank=True, max_length=100)),
                ('history_eye_disease', models.TextField(blank=True, default='NA')),
                ('history_eye_surgery', models.TextField(blank=True, default='NA')),
                ('uncorrected_vision_re', models.CharField(blank=True, max_length=20)),
                ('pinhole_vision_re', models.CharField(blank=True, max_length=20)),
                ('corrected_vision_re', models.CharField(blank=True, max_length=20)),
                ('uncorrected_vision_le', models.CharField(blank=True, max_length=20)),
                ('pinhole_vision_le', models.CharField(blank=True, max_length=20)),
                ('corrected_vision_le', models.CharField(blank=True, max_length=20)),
                ('dv_sph_re', models.CharField(blank=True, max_length=10)),
                ('dv_cyl_re', models.CharField(blank=True, max_length=10)),
                ('dv_axis_re', models.CharField(blank=True, max_length=10)),
                ('dv_vision_re', models.CharField(blank=True, max_length=10)),
                ('dv_sph_le', models.CharField(blank=True, max_length=10)),
                ('dv_cyl_le', models.CharField(blank=True, max_length=10)),
                ('dv_axis_le', models.CharField(blank=True, max_length=10)),
                ('dv_vision_le', models.CharField(blank=True, max_length=10)),
                ('nv_sph_re', models.CharField(blank=True, max_length=10)),
                ('nv_cyl_re', models.CharField(blank=True, max_length=10)),
                ('nv_axis_re', models.CharField(blank=True, max_length=10)),
                ('nv_vision_re', models.CharField(blank=True, max_length=10)),
                ('nv_sph_le', models.CharField(blank=True, max_length=10)),
                ('nv_cyl_le', models.CharField(blank=True, max_length=10)),
                ('nv_axis_le', models.CharField(blank=True, max_length=10)),
                ('nv_vision_le', models.CharField(blank=True, max_length=10)),
                ('performed_ar_assessment', models.BooleanField(default=False)),
                ('performed_refraction', models.BooleanField(default=False)),
                ('performed_schirmer', models.BooleanField(default=False)),
                ('performed_tbut', models.BooleanField(default=False)),
                ('performed_slit_lamp', models.BooleanField(default=False)),
                ('performed_fundus', models.BooleanField(default=False)),
                ('performed_iop', models.BooleanField(default=False)),
                ('schirmer_re', models.CharField(blank=True, max_length=50)),
                ('schirmer_le', models.CharField(blank=True, max_length=50)),
                ('tbut_re', models.CharField(blank=True, max_length=50)),
                ('tbut_le', models.CharField(blank=True, max_length=50)),
                ('slit_lamp_re', models.CharField(blank=True, default='NORMAL', max_length=100)),
                ('slit_lamp_le', models.CharField(blank=True, default='NORMAL', max_length=100)),
                ('fundus_re', models.CharField(blank=True, max_length=100)),
                ('fundus_le', models.CharField(blank=True, max_length=100)),
                ('iop_re', models.CharField(blank=True, max_length=50)),
                ('iop_le', models.CharField(blank=True, max_length=50)),
                ('provisional_diagnosis', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams_consulted', to=settings.AUTH_USER_MODEL)),
                ('optometrist', models.ForeignKey(limit_choices_to={'role': 'optometrist'}, on_delete=django.db.models.deletion.CASCADE, related_name='exams_conducted', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examinations', to='optometrist.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('quantity', models.CharField(blank=True, max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('eye', models.CharField(choices=[('Both eyes', 'Both eyes'), ('Right eye', 'Right eye'), ('Left eye', 'Left eye'), ('-', '-')], default='Both eyes', max_length=20)),
                ('duration', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('examination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='optometrist.eyeexamination')),
            ],
        ),
    ]
