# Generated by Django 5.1 on 2026-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0004_alter_patient_options_remove_patient_complaint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='diagnosis_notes',
            field=models.TextField(blank=True, help_text="Doctor's detailed observations and notes"),
        ),
    ]
