# Generated by Django 5.1 on 2026-02-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0005_eyeexamination_diagnosis_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optometrist',
            name='role',
            field=models.CharField(choices=[('optometrist', 'Optometrist'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='optometrist', max_length=20),
        ),
    ]
