# Generated by Django 5.1 on 2026-02-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0006_alter_optometrist_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Set to True when the doctor finalizes consultation'),
        ),
    ]
