# Generated by Django 6.0.1 on 2026-02-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0007_eyeexamination_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eyeexamination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optometrist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
