# Generated by Django 6.0.1 on 2026-03-21 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0008_alter_eyeexamination_id_alter_medication_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometrist',
            name='coins',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='optometrist',
            name='last_coin_login_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optometrist',
            name='last_coin_test_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
