# Generated by Django 5.1.5 on 2026-03-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0009_optometrist_coins_optometrist_last_coin_login_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='eye_health_rating',
            field=models.IntegerField(blank=True, help_text='Star rating out of 5', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='risk_factor',
            field=models.CharField(choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='low', help_text='Categorize patients based on risk for future segregation', max_length=20),
        ),
        migrations.AlterField(
            model_name='eyeexamination',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='medication',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='optometrist',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
