# Generated by Django 5.1.5 on 2026-04-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0010_eyeexamination_eye_health_rating_patient_risk_factor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometrist',
            name='retention_time',
            field=models.PositiveIntegerField(default=0, help_text='Total usage time in seconds'),
        ),
    ]
