# Generated by Django 5.1.5 on 2026-04-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0011_optometrist_retention_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='has_received_reward',
            field=models.BooleanField(default=False, help_text='Track if patient received coins for completing profile'),
        ),
    ]
