# Generated by Django 5.1.5 on 2026-04-18 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0012_patient_has_received_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='risk_factor',
            field=models.CharField(choices=[('not_classified', 'Not Classified'), ('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk')], default='not_classified', help_text='Categorize patients based on risk for future segregation', max_length=20),
        ),
    ]
