# Generated by Django 5.1.5 on 2026-04-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0013_alter_patient_risk_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='designation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='login_type',
            field=models.CharField(choices=[('at_home', 'At Home Login'), ('corporate', 'Corporate Login')], default='at_home', max_length=20),
        ),
    ]
