# Generated by Django 5.1.5 on 2026-04-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0014_patient_company_name_patient_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometrist',
            name='assigned_companies',
            field=models.TextField(blank=True, help_text='Comma-separated list of company names they work with', null=True),
        ),
        migrations.AddField(
            model_name='optometrist',
            name='working_hospital',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
