# Generated by Django 5.1.5 on 2026-04-19 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0015_optometrist_assigned_companies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Login Stat',
                'verbose_name_plural': 'User Login Stats',
                'unique_together': {('user', 'year_month')},
            },
        ),
    ]
