# Generated by Django 5.1.5 on 2026-04-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0016_userloginstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='optometrist',
            name='designation',
            field=models.CharField(choices=[('regular', 'Regular Optometrist'), ('corporate', 'Corporate Optometrist')], default='regular', max_length=20),
        ),
    ]
