# Generated by Django 6.0.1 on 2026-05-16 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("optometrist", "0018_alter_eyeexamination_id_alter_medication_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTopTen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "top_users_data",
                    models.JSONField(
                        default=list,
                        help_text="Stores a snapshot of the top 10 users for this day",
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily Top Ten",
                "verbose_name_plural": "Daily Top Tens",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="DailyUserUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("total_seconds", models.PositiveIntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Daily User Usage",
                "verbose_name_plural": "Daily User Usages",
                "ordering": ["-date", "-total_seconds"],
                "unique_together": {("user", "date")},
            },
        ),
    ]
