# Generated by Django 6.0.1 on 2026-06-13 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0019_dailytopten_dailyuserusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='cmp_type',
            field=models.CharField(blank=True, choices=[('cmp1', 'CMP1 - Standard Diabetic CMP'), ('cmp2', 'CMP2 - Advanced Diabetic CMP'), ('cmp3', 'CMP3 - Pediatric Myopia CMP')], help_text='The CMP program the patient is enrolled under (set during onboarding)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_cmp_patient',
            field=models.BooleanField(default=False, help_text='Whether this patient is enrolled in a Chronic Management Program (CMP)'),
        ),
        migrations.CreateModel(
            name='CMPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_type', models.CharField(choices=[('cmp1', 'CMP1 - Standard Diabetic CMP'), ('cmp2', 'CMP2 - Advanced Diabetic CMP'), ('cmp3', 'CMP3 - Pediatric Myopia CMP')], max_length=10)),
                ('hba1c_value', models.DecimalField(blank=True, decimal_places=1, help_text='HbA1c value (%)', max_digits=4, null=True)),
                ('hba1c_report', models.FileField(blank=True, null=True, upload_to='cmp/hba1c_reports/')),
                ('kft_report', models.FileField(blank=True, null=True, upload_to='cmp/kft_reports/')),
                ('diabetes_type', models.CharField(blank=True, choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=10, null=True)),
                ('current_diabetes_medications', models.TextField(blank=True, null=True)),
                ('has_kidney_disease', models.BooleanField(blank=True, help_text='Presence of kidney disease (Yes/No)', null=True)),
                ('exercise_frequency', models.CharField(blank=True, help_text='e.g. 3 times/week', max_length=100, null=True)),
                ('school_grade', models.CharField(blank=True, help_text='School grade / class', max_length=50, null=True)),
                ('axial_length', models.DecimalField(blank=True, decimal_places=2, help_text='Axial length (mm)', max_digits=4, null=True)),
                ('dilated_refraction', models.DecimalField(blank=True, decimal_places=2, help_text='Dilated refraction / spherical equivalent (D)', max_digits=5, null=True)),
                ('avg_daily_screen_time', models.DecimalField(blank=True, decimal_places=1, help_text='Average daily screen time (hours)', max_digits=4, null=True)),
                ('avg_daily_outdoor_time', models.DecimalField(blank=True, decimal_places=1, help_text='Average daily outdoor play time (hours)', max_digits=4, null=True)),
                ('eye_muscle_status', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('optometrist', models.ForeignKey(blank=True, help_text='Optometrist who recorded this entry', limit_choices_to={'role': 'optometrist'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cmp_records_entered', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cmp_records', to='optometrist.patient')),
            ],
            options={
                'verbose_name': 'CMP Clinical Record',
                'verbose_name_plural': 'CMP Clinical Records',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
