# Generated by Django 6.0.1 on 2026-06-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0020_patient_cmp_type_patient_is_cmp_patient_cmprecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='eyeexamination',
            name='allergies_with_medicine',
            field=models.TextField(blank=True, default='NA', help_text='Allergies (with medicine)'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_axis_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_axis_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_cyl_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_cyl_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_sph_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_sph_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_vision_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_dv_vision_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_axis_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_axis_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_cyl_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_cyl_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_sph_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_sph_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_vision_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='ar_nv_vision_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='conjunctiva_le',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='conjunctiva_re',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='cornea_le',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='cornea_re',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='eye_medication_used',
            field=models.TextField(blank=True, help_text='Medication used for the eye'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='family_history_eye_disease',
            field=models.TextField(blank=True, default='NA', help_text='Family history of eye disease'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='glasses_made_when_where',
            field=models.TextField(blank=True, help_text='When and where glasses were made'),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='iris_le',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='iris_re',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='lens_le',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='lens_re',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='outdoor_activity_hours',
            field=models.CharField(blank=True, help_text='Outdoor activities (children) in hours', max_length=100),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_axis_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_axis_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_cyl_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_cyl_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_sph_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_sph_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_vision_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_dv_vision_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_axis_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_axis_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_cyl_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_cyl_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_sph_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_sph_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_vision_le',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='pog_nv_vision_re',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='eyeexamination',
            name='systemic_medication',
            field=models.TextField(blank=True, default='NA', help_text='Systemic medication'),
        ),
    ]
