# Generated by Django 5.1.5 on 2026-08-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optometrist', '0020_alter_eyeexamination_id_alter_medication_id_and_more'),
        ('optometrist', '0021_eyeexamination_allergies_with_medicine_and_more'),
    ]

    operations = [
    ]
